stages:
    - build
    - deploy
    - checking

build:
    stage: build
    script:
        - yarn -DskipTests=true
    tags:
        - server

deploy:
    stage: deploy
    script:
        - yarn production
    tags:
        - server
