build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - yarn -DskipTests=true
        - yarn build
        - sudo mv -r build /data/trello-api/
        - sudo mv -r node_modules /data/trello-api/
    tags:
        - server
    
deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    when: manual
    before_script:
        - echo MONGODB_URI = ${MONGODB_URI} >> .env
        - echo DATABASE_NAME = ${DATABASE_NAME} >> .env
        - echo AUTHOR = ${AUTHOR} >> .env
        - echo PORT = ${PORT} >> .env
        - echo BUILD_MODE = ${BUILD_MODE} >> .env
    script:
        - sudo chown -r trello-api:trello-api /data/trello-api/
        - sudo su trello-api -c "nohup node ./build/src/server.js 2>&1 &"
    tags:
        - server
