build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - yarn -DskipTests=true
        - yarn build
    tags:
        - server
    
deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    before_script:
        - echo MONGODB_URI = ${MONGODB_URI} >> .env
        - echo DATABASE_NAME = ${DATABASE_NAME} >> .env
        - echo AUTHOR = ${AUTHOR} >> .env
        - echo PORT = ${PORT} >> .env
    script:
        - sudo cp build/ /data/trello-api/
        - sudo chown -R trello-api:trello-api /data/trello-api/
        - sudo su trello-api -c "cd /data/trello-api/; cross-env BUILD_MODE=production; nohup node ./build/src/server.js 2>&1 &"
    tags:
        - server
