stages:
    - build
    - deploy
    - checking

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - yarn -DskipTests=true
    tags:
        - server
    
deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    before_script:
        - cp ${ENV} .env
    script:
        - yarn production
    tags:
        - server
