stages:
    - build
    - deploy
    - checking

build:
    stage: build
    variables:
        GIT_STRATEGY: clone
    script:
        - yarn -DskipTests=true
    tags:
        - server
    
deploy:
    stage: deploy
    variables:
        GIT_STRATEGY: none
    before_script:
        - echo MONGODB_URI = ${MONGODB_URI} >> .env
        - echo DATABASE_NAME = ${DATABASE_NAME} >> .env
        - echo AUTHOR = ${AUTHOR} >> .env
        - echo PORT = ${PORT} >> .env
    script:
        - yarn production
    tags:
        - server
